### ISSUE TITLE
FRVT Ongoing API and other questions

### ISSUE THREAD

**Issue by jklontz** [TheMdTF/mdtf-public#18]
On behalf of Rank One Computing we are wondering if you are willing to accept FRVT Ongoing submissions. Every major face recognition vendor already supports this interface and software packaging structure, are you willing to accept conforming FRVT Ongoing submissions instead?

Does the test machine CPU support the FMA3 instruction set extension which is available on i7 CPUs starting in Haswell (2013)?

What assumptions can we make about software protection? Can we tie a license to a MAC address or USB dongle? It seems we can't make an internet connection to validate the license? What protections are in place to ensure the license is only used for this evaluation?

Apologies for the short notice on this feedback, we see that the API has been open to comment since November, though we were only conditionally accepted recently.

**Comment by JHowix** [comment]
Thanks Josh, answers below:

**"Are you willing to accept confirming FRVT ongoing submissions instead?"**  The FRVT and Rally Matching APIs have very different communication protocols.  We are asking for something that responds to HTTP requests, the FRVT SDK is something that can be called from C++.  Accepting just something that is wrapped solely in the FRVT API would require us to drastically alter the way we planned to pass data around for the evaluation.  

That being said, there is a current working example in the github of a dockerized application that conforms to the HTTP API, and calls a low level C++ API.  That API is not the FRVT API but its very close.  A small abstraction layer might provide what you are asking.

**"Does the test machine CPU support the FMA3 instruction set extension which is available on i7 CPUs starting in 2014?"**   We believe our hardware will support this.  We are happy to test a provided docker image any time between now and May 6th and provide confirmation.

**"What assumptions can we make about software protection?"** Software protection provisions are described in the CRADA.  Once available, please review and see if these are satisfactory.

**"Can we tie a license to a MAC address or USB dongle?"** No, we plan to evaluate your system in a distributed virtualized environment

**"It seems we can't make an internet connection to validate the license?"** Correct

**"What protections are in place to ensure the license is only used for this evaluation?"** In addition to those outlined in the CRADA, you may limit the license by date.  We are asking for a year from when testing starts.

**Comment by jklontz** [comment]
**"That being said, there is a current working example in the github of a dockerized application that conforms to the HTTP API, and calls a low level C++ API. That API is not the FRVT API but its very close. A small abstraction layer might provide what you are asking."**

This is actually part of what prompted the request, as it seemed to us you are close to being able to support this request, which would save us (and I presume other vendors) significant effort, with the added benefit of being able to cross-reference your results with NIST's.

We'll be sure to review the CRADA upon receipt, thank you.

**Comment by JHowix** [comment]
Just to give you a resolution on this, we will leave it open as a TODO but at the moment don't have any resources assigned to it on our end.  We are pretty booked up writing other software components for the test.  Thanks.

**Comment by blancharda** [comment]
I've opened #21 to address the FRVT abstraction as an enhancement for future rally events.
For now I will close this issue.
